### ISSUE TITLE
Create GitHub Action Workflow for pfs/black

### ISSUE THREAD

**Issue by atc0005** [atc0005/list-emails#16]
From https://github.com/psf/black#github-actions:

```yaml
# .github/workflows/black.yml

name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
```
